name: Visualize Performance Of Stocks On NGX
on:
  push:
    branches:
      - master  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Run Makefile 'all' target
      run: make all
   
        
     
     
  
    